name: ${project.name}
author: ${project.organization.name}
version: ${project.version}
main: ${project.groupId}.cosmiccraftweapons.${project.artifactId}Plugin

commands:
  weapons:
    aliases: [ccweapons, cosmicweapons, cosmiccraftweapons]
    description: Plugin main command.
  claim:
    aliases: [claimitem, claimitems]
    description: Claim command.

permissions:
  weapons.use:
    description: Permission to use plugin main command.
    default: op
  weapons.reload:
    description: Permission to reload the plugin.
    default: op
  weapons.claim:
    description: Permission to claim items.
    default: op